/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Stitch Brand Palette
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
        },
        slateBg: '#f8fafc',
        borderSubtle: '#e2e8f0',
        // Stitch Design Tokens
        "primary": "var(--primary, #4f46e5)",
        "primary-container": "var(--primary-container, #6366f1)",
        "on-primary": "var(--on-primary, #ffffff)",
        "on-primary-container": "var(--on-primary-container, #dad7ff)",
        "primary-fixed": "var(--primary-fixed, #e2dfff)",
        "primary-fixed-dim": "var(--primary-fixed-dim, #c3c0ff)",
        "on-primary-fixed": "var(--on-primary-fixed, #0f0069)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant, #3323cc)",
        "secondary": "var(--secondary, #00687a)",
        "secondary-container": "var(--secondary-container, #57dffe)",
        "secondary-fixed": "var(--secondary-fixed, #acedff)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim, #4cd7f6)",
        "on-secondary": "var(--on-secondary, #ffffff)",
        "on-secondary-container": "var(--on-secondary-container, #006172)",
        "on-secondary-fixed": "var(--on-secondary-fixed, #001f26)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant, #004e5c)",
        "tertiary": "var(--tertiary, #571ac0)",
        "tertiary-container": "var(--tertiary-container, #6f3dd9)",
        "tertiary-fixed": "var(--tertiary-fixed, #e9ddff)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim, #d0bcff)",
        "on-tertiary": "var(--on-tertiary, #ffffff)",
        "on-tertiary-container": "var(--on-tertiary-container, #e3d5ff)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed, #23005c)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant, #5516be)",
        "surface": "var(--surface, #f8f9ff)",
        "surface-dim": "var(--surface-dim, #cbdbf5)",
        "surface-bright": "var(--surface-bright, #f8f9ff)",
        "surface-container-lowest": "var(--surface-container-lowest, #ffffff)",
        "surface-container-low": "var(--surface-container-low, #eff4ff)",
        "surface-container": "var(--surface-container, #e5eeff)",
        "surface-container-high": "var(--surface-container-high, #dce9ff)",
        "surface-container-highest": "var(--surface-container-highest, #d3e4fe)",
        "surface-variant": "var(--surface-variant, #d3e4fe)",
        "surface-tint": "var(--surface-tint, #4d44e3)",
        "on-surface": "var(--on-surface, #0b1c30)",
        "on-surface-variant": "var(--on-surface-variant, #464555)",
        "on-background": "var(--on-background, #0b1c30)",
        "inverse-surface": "var(--inverse-surface, #213145)",
        "inverse-on-surface": "var(--inverse-on-surface, #eaf1ff)",
        "inverse-primary": "var(--inverse-primary, #c3c0ff)",
        "outline": "var(--outline, #777587)",
        "outline-variant": "var(--outline-variant, #c7c4d8)",
        "error": "var(--error, #ba1a1a)",
        "error-container": "var(--error-container, #ffdad6)",
        "on-error": "var(--on-error, #ffffff)",
        "on-error-container": "var(--on-error-container, #93000a)",

        ink: {
          950: '#04040a',
          900: '#080812',
          800: '#0d0d1f',
          700: '#12122e',
          600: '#1a1a3e',
        },
        signal: {
          DEFAULT: '#e8ff47',   // electric lime — primary accent
          dim: '#b8cc38',
        },
        ember: {
          DEFAULT: '#ff6b35',   // warm orange — secondary accent
          dim: '#cc5529',
        },
        mist: {
          900: '#9898b8',
          700: '#c4c4d8',
          500: '#dcdcec',
          100: '#f0f0f8',
        },
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'margin': '2rem',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        display: ['"Clash Display"', 'sans-serif'],
        body: ['Inter', '"Cabinet Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        sans: ['Inter', '"Cabinet Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'label-xs': ['10px', { lineHeight: '12px', fontWeight: '500' }],
        '10xl': ['10rem', { lineHeight: '0.9', letterSpacing: '-0.04em' }],
        '9xl':  ['8rem',  { lineHeight: '0.9', letterSpacing: '-0.04em' }],
        '8xl':  ['6rem',  { lineHeight: '0.92', letterSpacing: '-0.03em' }],
      },
      animation: {
        'marquee': 'marquee 25s linear infinite',
        'marquee-reverse': 'marquee 25s linear infinite reverse',
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 4s ease-in-out infinite',
        'spin-slow': 'spin 20s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      backgroundImage: {
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='1'/%3E%3C/svg%3E\")",
      },
    },
  },
  plugins: [],
}
